--DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  full_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  mobile VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

--DROP TABLE IF EXISTS TWEETER_SECRETS;
CREATE TABLE IF NOT EXISTS TWEETER_SECRETS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  userid VARCHAR(250) NOT NULL,
  consumerkey VARCHAR(250) NOT NULL,
  consumersecret VARCHAR(250) NOT NULL,
  token VARCHAR(250) NOT NULL,
  secret VARCHAR(250) NOT NULL
);